### ISSUE TITLE
1.4.0 breaks compatibility with PrestaShop < 1.7.7

### ISSUE THREAD

**Issue by JoshTheDerf** [PrestaShop/decimal#10]
I'm not sure if `prestashop/decimal` version 1.4.0 is intended to be compatible with PS 1.7.6.x. However, updating composer dependencies in PrestaShop 1.7.6.x pulls down version 1.4.0 of `prestashop/decimal`. The store will then crash whenever `extractMajorMinorDigits` in `src/Core/Localization/Number/Formatter.php` is called, as `extractMajorMinorDigits` expects to be passed an instance of `PrestaShop\Decimal\Number` but instead receives an instance of `PrestaShop\Decimal\DecimalNumber`, which PHP considers to be separate types.

Example error log:
```
2020/10/16 14:27:18 [error] 720#720: *576 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught TypeError: Argument 1 passed to PrestaShop\PrestaShop\Core\Localization\Number\Formatter::extractMajorMinorDigits() must be an instance of PrestaShop\Decimal\Number, instance of PrestaShop\Decimal\DecimalNumber given, called in src/Core/Localization/Number/Formatter.php on line 118 and defined in src/Core/Localization/Number/Formatter.php:173
Stack trace:
#0 src/Core/Localization/Number/Formatter.php(118): PrestaShop\PrestaShop\Core\Localization\Number\Formatter->extractMajorMinorDigits(Object(PrestaShop\Decimal\DecimalNumber))
#1 src/Core/Localization/Locale.php(155): PrestaShop\PrestaShop\Core\Localization\Number\Formatter->format(16.000001, Object(PrestaShop\PrestaShop\Core\Localization\Specification\Price))
#2 classes/Tools.php(776): PrestaShop\PrestaShop\Core\Localization\Locale->formatPrice(16.000001, 'USD')
#3 src/Adapter/Product/PriceFormatter.php(55): ToolsCore::displa" while reading response header from upstream
```

**Comment by CoralieNouletteAlbalogic** [comment]
Hi,
I have the same problem. Do you find any solution ?
`Type error: Argument 1 passed to PrestaShop\PrestaShop\Core\Localization\Number\Formatter::extractMajorMinorDigits() must be an instance of PrestaShop\Decimal\Number, instance of PrestaShop\Decimal\DecimalNumber given, called in /home/dev/dad/web/src/Core/Localization/Number/Formatter.php on line 118`

**Comment by Progi1984** [comment]
The version 1.4.0 for `prestashop/decimal` has been done for PrestaShop 1.7.8.x.

We had to change the class name because we have added static analysis with PHPStan. And there is no possible way to distinguish between either the PHP internal type or the custom class to use in the PHPDoc, so we rename PHP Class `Decimal` in `DecimalNumber`.

Source : https://phpstan.org/writing-php-code/phpdocs-basics#classes-named-after-internal-php-types

**Comment by PierreRambaud** [comment]
Don't forget PrestaShop is not a package. If you update dependencies, it can break everything, this is why we keep the composer.lock to be sure everything is working well :smile_cat:

**Comment by CoralieNouletteAlbalogic** [comment]
Thanks for your answers.

@Progi1984 :
I better understand the dependencies and the problem with this version. Thanks to you

I solved the problem by changing composer.json 
I changed
`"prestashop/decimal": "^1.2",`
to
`"prestashop/decimal": "1.2",`

And after a new composer install, it works again with vers 1.2 of prestashop/decimal

If it can help

**Comment by theMagnificientBoneless** [comment]
The version 1.2 must be installed as Required:

$ composer require prestashop/decimal:1.2

**Comment by PierreRambaud** [comment]
I'm closing it since the problem seems to be resolved
