### ISSUE TITLE
PhpStorm autocompletion with Number class.

### ISSUE THREAD

**Issue by bartvanhoutte** [PrestaShop/decimal#4]
Hello,

a bit of a weird support request. When I strictly type function arguments using the Number class, PhpStorm does not seem to be able to autocomplete the functions of the argument even though the code is legit and works. I have disabled all plugins and can't seem to get it fixed.

I have noticed the project uses namespace aliases for the Number class (DecimalNumber), this wouldn't happen to be for the same reason?

Thanks

**Comment by eternoendless** [comment]
Hi @bartvanhoutte, sorry for the delay!

I'm glad to see that you are using this library, I hope you're happy with it.

This is a [known issue with PhpStorm](https://youtrack.jetbrains.com/issue/WI-15619#focus=streamItem-27-2276596-0-0), which is why I used namespaces aliases for type hints.
