### ISSUE TITLE
Improvement helpers or Numbers

### ISSUE THREAD

**Issue by jolelievre** [PrestaShop/decimal#6]
The Decimal library is more and more integrated into the core project, which is a good thing
However some annoying use cases have happened quite a lot of times, although some workaround exist maybe we could improve this library to ease the word of developers. Here are some possible improvement:

# Lots of necessary forced casting

The Number class only uses string as input and output which forces casting lots of data.

## Build from float

```
$floatValue = 13.78965;
$numberValue = new Number((string) $floatValue);
```

### Suggestion

Adding a builder with float input
```
$numberValue = Number::fromFloat(13.78965);
```

## Output as float

Double casting is often used to cast number as float

```
$number = new Number('13.6786');
$floatValue = (float) (string) $number;
```

### Suggestion
```
$number = new Number('13.6786');
$floatValue = $number->toFloat();
```

# Compare with 0 values

Comparing a value to 0 is a very common action, sadly it forces creating a dedicated number in many places of the code. The `isNegative` `isPositive` methods are useless in those cases.

```
$orderTotalPaid = new Number('12.9786');
$zeroNumber = new Number('0');
if ($orderTotalPaid->isGreaterOrEqualThan($zeroNumber)) {
    ...
}
```

### Suggestion

We would need an instance of Number equal to 0 that is easily accessible, const is not possible but why not a static function?

```
$orderTotalPaid = new Number('12.9786');
if ($orderTotalPaid->isGreaterOrEqualThan(Number::zero())) {
    ...
}
```

# Other use cases

There are probably other things that could be improved..

**Comment by eternoendless** [comment]
I think that the fact that you need to cast from/to float is more likely a sign of another problem (using floats for decimal numbers) than a defect from this class. Including those helper methods just mask the problem: floats shouldn't be used for prices.

Regarding the "compare with zero" issues, I find the `Number::zero()` solution as equally verbose as `new Number('0')`. Maybe the best solution is to add new methods for  `isEqualToZero`, `isGreaterThanZero` & `isLowerThanZero`.

**Comment by jolelievre** [comment]
Yes it's almost as verbose but it was mainly to avoid instanciating a bunch of `Number('0')`
I thought about adding new methods but I thought it would complexify the class scope, but it's probably a better solution

Regarding the float input/output I guess it's mainly because for now we don't use Number everywhere so these convertions are still necessary for the transition period, when everything is based on Number I guess the output won't be useful any more

However the build from float might be handy if only for float values coming from database or ObjectModel, unless you think that the database structure should also evolve to storing price values as string?

**Comment by peldax** [comment]
@eternoendless  Hello, I would also welcome helper methods to avoid unnecessary casting.

- Sometimes I need to build DecimalNumber from float in order to compute some other information from price, for example price per meter is price divided by float which contains area.
- I also sometimes need to convert DecimalNumber to float. For example to output/cache/encode result from function above.

I understand the argument about losing the precision and that this library should not encourage it, but I believe that programmer which is not aware about floating point arithmetic and its gotchas is probably not going to use this library in the first place. On the other hand it would make some edge scenarios way easier.
